name: Export Godot game
description: Export Godot game.
inputs:
  platform:
    description: The game platform.
    required: true
  output:
    description: The game output.
    required: true
  version:
    description: The game version.
    required: true
  godot_version:
    description: The Godot version.
    required: true
  preset:
    description: The export preset.
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Build Info
      uses: robpc/godot-build-info-action@v1
      with:
        version: ${{ inputs.version }}

    - name: Setup Godot Templates
      shell: bash
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable ~/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable

    - name: Install Addons
      shell: bash
      run: |
        [ -f plug.gd ] && godot --headless -s plug.gd install || true

    - name: Import Assets
      shell: bash
      run: |
        godot --editor --quit --headless

    - name: Build ${{ inputs.preset }}
      shell: bash
      run: |
        [ -d build ] && rm -r build
        mkdir -v -p build/${{ matrix.platform }}
        godot --export-release "${{ inputs.preset }}" --headless ./build/${{ matrix.platform }}/${{ inputs.output }}
